In [1]:
import pandas as pd

In [2]:
pd.__version__

'1.4.1'

In [3]:
import numpy as np

In [4]:
np.__version__

'1.22.3'

# Pandas对象简介

## Pandas的Series对象

Pandas的Series对象是一个带索引数据构成的一维数组。可以用一维数组创建Series对象。

In [5]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])

In [6]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [7]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [8]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
data[1]

0.5

In [10]:
data[1:3]

1    0.50
2    0.75
dtype: float64

Series对象的索引可以是任意想要的类型，比如：字符串。

In [11]:
data = pd.Series(data.to_list(), index=list("abcd"))

In [12]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [13]:
data['b']

0.5

或者使用不连续或不按顺序的索引。

In [14]:
data = pd.Series(data.values, index=[2,5,3,7])

In [15]:
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

我们可以直接用Python的字典创建一个Series对象。

In [16]:
population_dict = {
    'California': 38332521,
    'Texas': 26448193,
    'New York': 19651127,
    'Florida': 19552860,
    'Illinois': 12882135
}

In [17]:
population = pd.Series(population_dict)

In [18]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [19]:
population['California']

38332521

In [20]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

我们可以用如下的方式创建Series对象：

```Python
pd.Series(data, index=index)
```

其中，index是一个可选参数，data参数支持多种数据类型，比如列表或NumPy数组，此时index默认值为整数序列。

In [21]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [22]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [23]:
pd.Series({2: 'a', 1: 'b', 3: 'c'})

2    a
1    b
3    c
dtype: object

In [24]:
pd.Series({2: 'a', 1: 'b', 3: 'c'}, index=[3, 2])

3    c
2    a
dtype: object

## Pandas的DataFrame对象

In [25]:
area_dict = {'California': 423967, 'Texas': 695662, 
             'New York': 141297, 'Florida': 170312,
             'Illinois': 149995
            }

In [26]:
area = pd.Series(area_dict)

In [27]:
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [28]:
states = pd.DataFrame({'population': population,
                       'area': area
                      })

In [29]:
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [30]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [31]:
states.columns

Index(['population', 'area'], dtype='object')

In [32]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

创建DataFrame对象

1. 通过单个Series对象创建
2. 通过字典列表创建
3. 通过Series对象字典创建
4. 通过NumPy二维数组创建
5. 通过NumPy结构化数组创建

通过单个Series对象创建:

In [33]:
pd.DataFrame(population, columns=['polulation'])

polulation
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [34]:
pd.DataFrame(population, columns=['abc'])

abc
California  38332521
Texas       26448193
New York    19651127
Florida     19552860
Illinois    12882135

通过字典列表创建:

In [35]:
data = [{'a': i, 'b': 2 * i} for i in range(3)]

In [36]:
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [37]:
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [38]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

通过Series对象字典创建:

In [39]:
pd.DataFrame({'population': population, 
              'area': area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

通过NumPy二维数组创建:

In [40]:
pd.DataFrame(np.random.rand(3, 2),
            columns=['foo', 'bar'],
            index=['a', 'b', 'c'])

foo       bar
a  0.399247  0.177869
b  0.429178  0.871498
c  0.662289  0.792003

通过NumPy结构化数组创建:

In [41]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])

In [42]:
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [43]:
np.zeros(3)

array([0., 0., 0.])

In [44]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

## Pandas的Index对象

In [45]:
ind = pd.Index([2, 3, 5, 7, 11])

In [46]:
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [47]:
ind[3]

7

In [48]:
ind.size, ind.shape, ind.ndim, ind.dtype

(5, (5,), 1, dtype('int64'))

In [49]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [50]:
# 交集
indA & indB 

/var/folders/jm/m_xtkvhx6w72_r8ylr5jx8b40000gn/T/ipykernel_91916/397782739.py:2: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead.
  indA & indB


Int64Index([3, 5, 7], dtype='int64')

In [51]:
# 并集
indA | indB

/var/folders/jm/m_xtkvhx6w72_r8ylr5jx8b40000gn/T/ipykernel_91916/1780210416.py:2: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead.
  indA | indB


Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [52]:
# 异或
indA ^ indB

/var/folders/jm/m_xtkvhx6w72_r8ylr5jx8b40000gn/T/ipykernel_91916/514356942.py:2: FutureWarning: Index.__xor__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__xor__.  Use index.symmetric_difference(other) instead.
  indA ^ indB


Int64Index([1, 2, 9, 11], dtype='int64')

In [53]:
indA.intersection(indB)

Int64Index([3, 5, 7], dtype='int64')

# 数据取值与选择

## Series数据选择方法

In [54]:
data = pd.Series([.25, .5, .75, 1.0], index=list('abcd'))

将Series看作字典

In [55]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [56]:
data['b']

0.5

In [57]:
'a' in data

True

In [58]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [59]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [60]:
data['e'] = 1.25

将Series看作一维数组

In [61]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [62]:
data[0:2]

a    0.25
b    0.50
dtype: float64

In [63]:
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [64]:
data[['a','e']]

a    0.25
e    1.25
dtype: float64

索引器: loc和iloc

In [65]:
data = pd.Series(list('abc'), index=[1,3,5])

In [66]:
data

1    a
3    b
5    c
dtype: object

In [67]:
data.loc[1]

'a'

In [68]:
data.loc[1:5]

1    a
3    b
5    c
dtype: object

In [69]:
data.iloc[1]

'b'

In [70]:
data.iloc[1:3]

3    b
5    c
dtype: object

## DataFrame数据选择方法

将DataFrame看作字典

In [71]:
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [72]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [73]:
data = pd.DataFrame({'area': area, "pop": population})

In [74]:
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [75]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [76]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [77]:
data.area is data['area']

True

In [78]:
data['density'] = data['pop'] / data['area']

In [79]:
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

将DataFrame看作二维数组

In [80]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [81]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [82]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [83]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [84]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [85]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

其他取值方法

In [88]:
data['Florida':'Illinois']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [89]:
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [90]:
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

# Pandas数值运算方法

In [91]:
rng = np.random.RandomState(42)

In [92]:
ser = pd.Series(rng.randint(0, 10, 4))

In [93]:
ser

0    6
1    3
2    7
3    4
dtype: int64

In [94]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)), columns=list("ABCD"))

In [95]:
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [96]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [97]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16